stages:
  - build

Build:
  stage: build
  variables:
    GIT_SSL_NO_VERIFY: "true"
  image:
    name: kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --single-snapshot
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  tags:
    - app
  only:
    - master
