# Generated by Django 5.0.4 on 2024-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorValueView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('actives', models.DecimalField(decimal_places=2, max_digits=20)),
                ('loan_portfolio_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reverse_repo_operations', models.DecimalField(decimal_places=2, max_digits=20)),
                ('late_payments_7_sum', models.DecimalField(decimal_places=2, max_digits=20)),
                ('late_payments_7_portfolio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('late_payments_30_sum', models.DecimalField(decimal_places=2, max_digits=20)),
                ('late_payments_30_portfolio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('late_payments_90_sum', models.DecimalField(decimal_places=2, max_digits=20)),
                ('late_payments_90_portfolio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_remuneration', models.DecimalField(decimal_places=2, max_digits=20)),
                ('provision_requirements', models.DecimalField(decimal_places=2, max_digits=20)),
                ('liabilities', models.DecimalField(decimal_places=2, max_digits=20)),
                ('contributions_individuals', models.DecimalField(decimal_places=2, max_digits=20)),
                ('contributions_legal_entities', models.DecimalField(decimal_places=2, max_digits=20)),
                ('equity_on_balance_sheet', models.DecimalField(decimal_places=2, max_digits=20)),
                ('excess_of_income_tax', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'analytic_indicator_value_view',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='report',
            name='banks',
            field=models.ManyToManyField(db_table='analytic_report_banks', to='analytic.bank'),
        ),
    ]
